fix Arabic mistakes and add Arabic currency
joke2k/faker pull request #1328
Opened 2020-11-27 07:16 UTC by itsmohmans

### What does this change
One change to [providers/persons/ar_AA/__init__.py](https://github.com/joke2k/faker/blob/594d34414b/faker/providers/person/ar_AA/__init__.py)
I also added a new currency for Arabic ar_AA

### What was wrong
There was a wrong name in [providers/persons/ar_AA/__init__.py](https://github.com/joke2k/faker/blob/594d34414b/faker/providers/person/ar_AA/__init__.py)

### Note
This is my very first contribution to a project.

2020-11-30 15:40 UTC, fcurella commented
Thank you! Could add some tests for the new currency provider?

2020-11-30 15:46 UTC, itsmohmans commented
Can you guide me more on where to add the tests? As I didn't really dig into this project I just localized it. Thanks.

2020-11-30 15:54 UTC, fcurella commented
You can copy and modify any of the existing tests for the other currency providers, eg the [Russian](https://github.com/joke2k/faker/blob/master/tests/providers/test_currency.py#L71-L90) one.

2020-11-30 16:12 UTC, itsmohmans commented
Done.

2020-12-04 17:18 UTC, fcurella requested changes

2020-12-04 17:18 UTC, fcurella commented on tests/providers/test_currency.py
> +            assert isinstance(cur, tuple) and cur in self.currencies
can you split this assertion?

```suggestion
            assert isinstance(cur, tuple)
            assert cur in self.currencies
```

2020-12-04 17:18 UTC, fcurella commented on tests/providers/test_currency.py
> +            assert isinstance(name, str) and name in self.currency_names
Same as above:

```suggestion
            assert isinstance(name, str)
            assert name in self.currency_names
```

2022-04-16 02:01 UTC, closed without merging