Added Assert statement used outside of tests
joke2k/faker pull request #1331
Opened 2020-11-30 09:32 UTC by HarshCasper

### What does this changes

I have added Assert statement used outside of tests. This usually follows the modern standards where the assert keyword should be used when failure to meet a condition violates the integrity of the program. 

### What was wrong

In the original Code, asserts were used outside of the Tests. 

### How this fixes it

I have added the Assert Statement used outside of tests by refactoring the Code. 

----------------
I ran a DeepSource Analysis on my fork of this repository. You can see all the issues raised by DeepSource [here](https://deepsource.io/gh/HarshCasper/faker/).

There are plenty of other issues in relation to Bug Discovery, Performance and Anti-Patterns which you would be interested to take a look at.

If you do not want to use DeepSource to continuously analyze this repo, I'll remove the `.deepsource.toml` from this PR and you can merge the rest of the fixes. If you want to setup DeepSource for Continuous Analysis, I can help you set that up.

2020-11-30 15:51 UTC, fcurella commented
Thank you @HarshCasper !

I'm not sure I understand the difference between using `assert` vs `if ...: raise AssertionError()`. I personally find `assert` more concise and readable, but maybe it's just me?

2020-12-14 10:17 UTC, HarshCasper commented
Hello @fcurella 

Basically, Python has an option to compile the optimized bytecode and create the respective .pyo files by using the options -O and -OO. During this process, the Assert statements are removed, and if getting the compiled bytecode, is not an intention, this issue can be ignored. But in the other case, it might cause problems if used in non-test files. That is why it is explicitly checked and a respective Error is raised using an if statement.

2021-01-20 01:36 UTC, bact commented on faker/utils/distribution.py
> +        raise AssertionError("You can't request more unique samples than elements in the dataset.")
should this be ValueError instead?

2021-01-21 15:44 UTC, fcurella commented
@HarshCasper I'm ok with adding DeepSource to the CI, but I would add it in a separate PR.

2021-01-22 02:39 UTC, HarshCasper commented
> @HarshCasper I'm ok with adding DeepSource to the CI, but I would add it in a separate PR.

@fcurella Should I make a separate PR for the same?

2021-02-20 09:38 UTC, HarshCasper commented
Hi @fcurella 

Can you kindly have a look at this again! Thanks :)

2021-02-23 15:07 UTC, fcurella requested changes

2021-02-23 15:07 UTC, fcurella commented on .deepsource.toml
> +  runtime_version = "3.x.x"
Could you move the deepsource config out of this PR and into one of its own?

2021-06-27 18:59 UTC, closed without merging