Extend Pesel To support greater range of dates
joke2k/faker pull request #1426
Opened 2021-04-09 09:00 UTC by IlfirinPL

Add support for following section  from page https://en.wikipedia.org/wiki/PESEL

Birthdates
The PESEL system has been designed to cover five centuries. To distinguish people born in different centuries, numbers are added to the MM field:

for birthdates between 1900 and 1999 – no change to MM field is made (see below)
for other birthdates:
2000–2099 – month field number is increased by 20
2100–2199 – month + 40
2200–2299 – month + 60
1800–1899 – month + 80

### What does this changes

Brief summary of the changes

### What was wrong

Description of what was the root cause of the issue.

### How this fixes it

Description of how the changes fix the issue.

Fixes #...

2021-04-12 15:41 UTC, fcurella requested changes
Thank you! Could you add some tests for these scenarios?

2021-04-12 18:10 UTC, IlfirinPL commented
@fcurella  Yes, Will write some tests

2021-04-13 08:32 UTC, IlfirinPL commented
@fcurella  Tests added, documentation for function also update.

2021-04-13 09:29 UTC, IlfirinPL commented
@fcurella  
I see that formater on windows doesn't like dates old dates  "format %y requires year >= 1900 on Windows"
https://ci.appveyor.com/project/joke2k/faker/builds/38675793/job/kue9e4iel8w4nwyb#L1364
what do you this should be done skip those tests for windows or change way of extraction of values ?

2021-04-13 14:01 UTC, IlfirinPL commented
Update code with workaround issue with dates below 1900

2021-04-13 21:15 UTC, fcurella commented
Thank you!

2021-04-13 21:16 UTC, merged