Fix/master/aba routing
joke2k/faker pull request #1443
Opened 2021-05-14 15:40 UTC by mstellon

### What does this changes

Added aba() function to bank provided to generate valid ABA routing numbers. https://en.wikipedia.org/wiki/ABA_routing_transit_number

Fixes #1437

2021-05-18 14:23 UTC, fcurella requested changes
Could you fix the linting issues?

2021-05-18 14:26 UTC, fcurella commented on faker/providers/bank/__init__.py
> +
Can you remove those two blank lines?

2021-05-18 14:26 UTC, fcurella commented on faker/providers/bank/__init__.py
> +from math import ceil
we use `isort` to sort imports. Can you move this import down to Line 5? (there should be a blank line between the `import ...` block and the `from ... import ...` block)

2021-06-04 17:32 UTC, mstellon commented
Fixed linting issues. Thanks!

2021-06-04 19:05 UTC, fcurella commented
Thank you!

2021-06-04 19:06 UTC, merged