Fix #1458. Change fi_FI Provinces to Regions
joke2k/faker pull request #1459
Opened 2021-06-11 08:32 UTC by LKajan

### What does this changes

Changes the list of provinces to a list of regions.

### What was wrong

Finnish Provinces were abolished in 2009.

### How this fixes it

Now `administrative_unit()` and `state()` returns current regions.

Fixes #1458

2021-06-11 14:13 UTC, fcurella requested changes

2021-06-11 14:13 UTC, fcurella commented on faker/providers/address/fi_FI/__init__.py
> +        'Varsinais-Suomi'
Could you add a trailing comma here?

```suggestion
        'Varsinais-Suomi',
```

2021-06-11 21:42 UTC, fcurella approved these changes

2021-09-15 17:07 UTC, fcurella commented
Thank you! Sorry this fell through the crack and I didn't merge it sooner!

2021-09-15 17:07 UTC, merged

2021-09-17 06:22 UTC, LKajan commented
Thanks @fcurella for merging!