Fix siret and siren generation for fr_FR locale company information
joke2k/faker pull request #1465
Opened 2021-06-12 21:42 UTC by babastienne

### What does this changes

Fix SIREN and SIRET generation for company fr_FR.

The twoo fields ned to respect the luhn algorythm to be valid.

### What was wrong

The two fields where generated randomly and therefore were not valid.

### How this fixes it

Integrate the luhn control number at the end of each field.

More information about this fix on the related issue #1445

2021-06-14 15:02 UTC, fcurella requested changes
Thank you! Could you add a test that checks if the checksum is valid?

2021-06-14 15:02 UTC, fcurella commented on faker/providers/company/fr_FR/__init__.py
> +        The siret number is formated as '### ### ### #####'.
```suggestion
        The siret number is formatted as '### ### ### #####'.
```

2022-04-11 02:08 UTC, closed without merging

2022-12-20 09:25 UTC, gp4git commented
Hi,
I need this fix.
Is it possible to release it ?

Regards

2022-12-20 09:32 UTC, stefan6419846 commented
The author @babastienne apparently never answered back on the request from @fcurella to add a corresponding test and to fix the typo. Feel free to submit an improved version of this PR yourself for future inclusion into a released package version.

2022-12-20 10:13 UTC, gp4git commented
Hi Stefan,
unfortunetaly, i'm not a python developer but I can confirm that this current PR fixed the bug.
I tested it across a python script (populate.py) that uses python3 faker which is released 
with a PostgreSQL extension called "postgresql_anonymizer".
So, for me, except for the typo, this current PR solves the problem.

Regards

2022-12-20 10:19 UTC, stefan6419846 commented
This is no current PR, but has been closed about half a year ago, while being created more than a year ago.

Unfortunately, the bug which has been fixed here is not represented by a test, especially that the checksum actually is correct, as pointed out by Flavio above. Adding this should not be a big deal when looking at the existing tests if one is familiar enough with SIRET and SIREN numbers, which I am not.

2022-12-28 18:48 UTC, daamien commented
As far as i can tell, the test would be 

```python
from faker import Faker
from faker.utils.checksums import luhn_checksum
luhn_checksum(Faker('fr_FR').siret().replace(' ','')) == 0
```