Improve phone numbers for it_IT
joke2k/faker pull request #1587
Opened 2022-01-03 21:52 UTC by FrancYescO

Implement https://github.com/joke2k/faker/issues/1586

2022-01-03 22:26 UTC, fcurella requested changes

2022-01-03 22:26 UTC, fcurella commented on faker/providers/phone_number/it_IT/__init__.py
> +        "330#", "331#", "333#", "334#", "335#", "336#", "337#", "338#", "339#", "360#", "361#", "362#", "363#", "366#", "368#", "381#", "385#",
line too long here https://github.com/joke2k/faker/runs/4696003420?check_suite_focus=true#step:5:15

2022-01-03 22:26 UTC, fcurella commented on faker/providers/phone_number/it_IT/__init__.py
> +        "320#", "322#", "323#", "324#", "327#", "328#", "329#", "355#", "380#", "388#", "389#", "390#", "391#", "392#", "393#", "397#",
line too long here https://github.com/joke2k/faker/runs/4696003420?check_suite_focus=true#step:5:16

2022-01-03 22:42 UTC, fcurella requested changes
Could you run your code through the linters? the `Makefile` has a `lint` task that you can run with `make lint`, provided you have `isort`, `black` and `mypy` installed.

2022-01-04 09:44 UTC, FrancYescO commented
@fcurella is still something needed?

2022-01-04 16:42 UTC, fcurella commented
Looks good! Thank you!

2022-01-04 16:42 UTC, merged