add geonames db of italian cap-city-province and full match when generating full address
joke2k/faker pull request #1593
Opened 2022-01-07 22:32 UTC by FrancYescO

also improved format for building_number_formats and secondary_address_formats

Maybe the code can be improved but ... 🤷

Fix (at least for italy) https://github.com/joke2k/faker/issues/1585

PS. i've used this snippet to "convert to dictionary" the geonames db
```
import csv
fulldict = {}
with open('IT.txt', newline = '') as games:                                                                                          
	game_reader = csv.reader(games, delimiter='\t')
	for game in game_reader:
		if game[1] not in fulldict:
			fulldict[game[1]] = [[game[2],game[6]]]
		else:
			fulldict[game[1]].append([game[2],game[6]])

print(fulldict)
```

2022-01-07 22:36 UTC, FrancYescO commented
> faker/providers/phone_number/en_PH/__init__.py:17:121: E501 line too long (122 > 120 characters)

dafaq? en_PH was jus untouched..

2022-01-13 15:41 UTC, fcurella requested changes
Can you add some tests for `postcode_city_province` and `city`?

2022-01-13 15:41 UTC, fcurella commented on faker/providers/address/it_IT/__init__.py
> +    def city(self):
can you add a type hint here too?

```suggestion
    def city(self) -> str:
```

2022-01-13 15:41 UTC, fcurella commented on faker/providers/address/it_IT/__init__.py
> +        rand_city_prov = self.random_element(self.cap_city_province[cap])  # type: List[str]
we fully support type hints, so you dont need the py2-compatible syntax
```suggestion
        rand_city_prov: List[str] = self.random_element(self.cap_city_province[cap])
```

2022-01-13 15:42 UTC, fcurella commented
@FrancYescO  Don't worry about that extra commit, we're going to squash them anyway. But please let's keep the comments family-friendly :)

2022-01-13 15:49 UTC, FrancYescO commented
> Can you add some tests for `postcode_city_province` and `city`?

can you suggest a good place for the test case?

2022-01-13 16:43 UTC, fcurella commented
@FrancYescO You should add a testcase in [tests/providers/test_address.py](https://github.com/joke2k/faker/blob/master/tests/providers/test_address.py)

2022-01-13 21:57 UTC, fcurella commented
Perfetto! Grazie! <3

2022-01-13 21:58 UTC, merged