Initial creation of fr_CA locale for Address
joke2k/faker pull request #1594
Opened 2022-01-19 23:20 UTC by mbeaty-sf

### What does this changes

Address French Canadian Address formats to fr_CA

### What was wrong

The addresses that were being created were not properly reflecting Canadian Provinces/Cities or French Canadian address formats

### How this fixes it

Created updates to allow for the formatting, suffixes, and prefixes of Canadian French addresses

Fixes #...

2022-01-24 16:39 UTC, fcurella requested changes
can you add tests for the new provider?

2022-02-04 15:35 UTC, fcurella commented on faker/providers/address/fr_CA/__init__.py
> +        :example: 'rue'
is "rue" a city prefix?

2022-02-04 15:38 UTC, fcurella requested changes
Could you run `make lint` and fix the issues?

2022-03-25 21:55 UTC, fjudith commented
@mbeaty-sf  would be great if you can get this merge

2022-07-08 02:13 UTC, closed without merging