Use os.urandom in binary, add binary_seeded
joke2k/faker pull request #1605
Opened 2022-02-03 23:09 UTC by AlmightyYakob

### What does this change

Updates the `binary` method, preserving the old functionality in the `binary_seeded` method.

### What was wrong

The existing code for the `binary` method is very slow (30-40x slower!) compared to `os.urandom`. For anything larger than a trivial amount of bytes, the list comprehension adds a very large amount of overhead.

### How this fixes it

Uses `os.urandom` to generate random bytes in the `binary` method, instead of iterating over `length` calling `randrange`.

I would suspect that more people care about the speed of this method than the ability to seed it, but I could be wrong about that. If that's the case, this implementation could be flipped, with a `binary_fast` method instead.

2022-02-04 16:40 UTC, AlmightyYakob commented
> Could we modify [`seed`](https://github.com/joke2k/faker/blob/master/faker/generator.py?rgh-link-date=2022-02-04T15%3A58%3A03Z#L72-L73) and [`seed_instance`](https://github.com/joke2k/faker/blob/master/faker/generator.py?rgh-link-date=2022-02-04T15%3A58%3A03Z#L62-L69) to set something like`cls._is_seeded = True`, and use that property to automatically switch behavior?

I think that'd be ideal. I had a similar idea but wasn't familiar enough with the codebase to seriously propose it.

2022-02-04 19:01 UTC, fcurella requested changes
You'll need to update the tests as well, since the data will change

2022-02-08 17:24 UTC, AlmightyYakob commented
@fcurella I've fixed the tests, I was initializing the `_is_seeded` var wrong. However, now calling `seed` will set this var for all faker instances, without any real way to reset it. Is this expected/desired?

2022-02-15 15:15 UTC, fcurella approved these changes

2022-02-15 19:38 UTC, merged