Creating maximal and minimal lenght for providers
joke2k/faker pull request #1615
Opened 2022-02-11 17:35 UTC by Kalbra

This PR works on #1506 by adding maximal and minimal lenght for providers

2022-02-14 19:06 UTC, Kalbra commented on faker/providers/__init__.py
> +                    if len(element) >= min_element_length:
Well it somehow works, but I get what you mean. I changed that in [28087b4](https://github.com/joke2k/faker/pull/1615/commits/28087b4a77f449b616d4c10d430417734d093e18) by using a more logic way.

2022-02-14 19:15 UTC, Kalbra commented on faker/providers/person/__init__.py
> +            suffixes: Sequence[ElementsType] = self.suffixes_male
Even if I do not know exactly what `# type: ignore[attr-defined]` do I added it at [d7dc9d9](https://github.com/joke2k/faker/pull/1615/commits/d7dc9d90d8c3b458587f73358c4595e85fde1c91) to prefix and suffix.

2022-02-15 15:09 UTC, fcurella requested changes

2022-02-16 21:52 UTC, Kalbra commented
I was just thinking about using args and kwargs instead of `min_length: Optional[int] = None, max_length: Optional[int] = None`
because then it would be easier to add parameters for future features.
@fcurella what do you think?

2022-02-17 17:49 UTC, Kalbra commented on faker/providers/person/__init__.py
> +            prefixes.update(self.prefixes_female)
I added this in [53f2530](https://github.com/joke2k/faker/pull/1615/commits/53f2530c504b85377766d32f3dec159d94620532)

2022-02-22 15:54 UTC, fcurella commented
@Kalbra 
> I  was just thinking about using args and kwargs

Wouldn't that break automcompletion with mypy? I'd rather keep the arguments explicit.

2022-02-25 20:25 UTC, Kalbra commented
@fcurella 
> Wouldn't that break automcompletion with mypy? I'd rather keep the arguments explicit.

Good point, makes sense to me, so I will keep the arguments explicit.

2022-05-11 11:31 UTC, MetcalfeTom commented
Is this PR still in active development?  Would be a very useful feature for our team.

If it is abandoned, I'd be happy to contribute myself

2022-05-16 13:17 UTC, fcurella commented
Closed in favor of https://github.com/joke2k/faker/pull/1662

2022-05-16 13:17 UTC, closed without merging