Update spanish phone number formats
joke2k/faker pull request #1763
Opened 2022-12-13 16:52 UTC by GuillemCalidae

According to the official specs:
https://avancedigital.mineco.gob.es/es-ES/Servicios/Numeracion/Documents/Guia_Numeracion.pdf

### What does this change

Adds restrictions to some phone numbers generations.

### What was wrong

Some phone numbers generated weren't valid according to official documentation. While the whole 8- and 9- prefixes are supposed to be landline numbers not all following numbers are assigned to an actual geographic area and are invalid.

### How this fixes it

Add phone numbers prefixes to increase the specificity of the numbers generated.

Also refactored the formats tuple to be generated from a product of prefixes and phone numbers, which makes sense now to avoid a list of 400+ elements.

2023-01-09 17:17 UTC, fcurella requested changes
Can you run `make lint` to fix the formatting issues?

2023-01-10 11:13 UTC, n1ngu requested changes

2023-01-10 11:13 UTC, n1ngu commented on faker/providers/phone_number/es_ES/__init__.py
> +        f'{phone_format.replace("xxx", prefix)}'
Or simply
```
    formats = tuple(
        phone_format.replace("xxx", prefix)
        for (prefix, phone_format) in itertools.product(PREFIXES, PHONE_FORMATS)
    )
```

2023-01-11 14:36 UTC, fcurella approved these changes
Thank you!

2023-01-11 14:37 UTC, merged