Add fr ca date time provider
joke2k/faker pull request #1766
Opened 2022-12-14 15:48 UTC by davebulaval

See issue #1764 for detail.

2022-12-14 15:51 UTC, davebulaval commented
I was unsure if you wanted to duplicate the `TestFrFr` for coverage purposes. I think the less we can do is to add a mention of the shared format. Also, I have renamed the `TestFrFr` to `TestFrFrAndFrCa` to reflect this shared format.

2022-12-17 03:09 UTC, davebulaval commented
Not quite sure of the failure reason.

2023-01-09 18:58 UTC, fcurella requested changes

2023-01-09 20:06 UTC, davebulaval commented on tests/providers/test_date_time.py
> +class TestFrFrAndFrCa(unittest.TestCase):
Perfect. I will duplicate the tests later today.

2023-01-09 22:33 UTC, davebulaval commented on tests/providers/test_date_time.py
> +class TestFrFrAndFrCa(unittest.TestCase):
@fcurella done!

2023-01-10 15:55 UTC, fcurella approved these changes

2023-01-10 15:56 UTC, fcurella approved these changes
Thank you!

2023-01-10 15:56 UTC, merged