Fix siret and siren generation for fr_FR locale company information
joke2k/faker pull request #1773
Opened 2022-12-29 15:23 UTC by daamien

Hi !

This is a new attempt to fix the French SIRET/SIREN generation.

The correction was first submitted in MR #1465 in 2021 but never merged

I simply did a rebase from the master branch and I added basic tests

2022-12-30 08:41 UTC, stefan6419846 commented on faker/providers/company/fr_FR/__init__.py
> +        Generates a siren number (9 digits). Formated as '### ### ###'.
Should probably read `Formatted` instead.

2022-12-30 08:41 UTC, stefan6419846 commented on tests/providers/test_company.py
> +            assert luhn_checksum(siren.replace(' ','')) == 0
These should probably read `siren.replace(' ', '')` instead.

2023-01-09 18:46 UTC, fcurella requested changes
can you run `make lint` to fix the formatting issues?

2023-01-11 13:15 UTC, daamien commented
> can you run `make lint` to fix the formatting issues?

done !

2023-01-24 16:38 UTC, merged