Add nl_BE company provider
joke2k/faker pull request #1811
Opened 2023-02-28 13:19 UTC by takis

2023-03-03 16:29 UTC, fcurella requested changes
Could you add a test case for the new provider?

2023-03-13 13:27 UTC, takis commented
Hi Flavio,

I've just added a test case for the new company provider.

2023-03-14 15:24 UTC, fcurella approved these changes

2023-03-20 16:50 UTC, fcurella approved these changes
Thank you!

2023-03-20 16:50 UTC, merged