Added es_PE person
joke2k/faker pull request #1844
Opened 2023-04-10 17:54 UTC by JsonVladimir

Added es_PE to person, I recently used the library and noticed that there were no common names from Peru, I decided to propose that the file be added.

2023-04-13 14:01 UTC, fcurella requested changes
Could you add some test cases for the new providers?

2023-04-24 16:00 UTC, fcurella requested changes
Can yuou fix the remaining linting issue? You can run `make lint` to format using the project's settings.

2023-04-26 15:51 UTC, JsonVladimir commented
> Can yuou fix the remaining linting issue? You can run `make lint` to format using the project's settings.

When I run black it tells me there is 1 file that needs to be reformatted but when i format it it tells me no changes were made.

```
C:\GitHub\faker> python -m black --check --line-length 120 C:\GitHub\faker
would reformat C:\GitHub\faker\tests\providers\test_phone_number.py

Oh no! 💥 💔 💥
1 file would be reformatted, 683 files would be left unchanged.
C:\GitHub\faker> python -m black C:\GitHub\faker\tests\providers\test_phone_number.py
**All done! ✨ 🍰 ✨
1 file _left unchanged_.**
```
![image](https://user-images.githubusercontent.com/129775146/234630818-cafe7408-8651-4eae-9121-713ca0e20f3f.png)
![image](https://user-images.githubusercontent.com/129775146/234630869-2a148307-c2a6-4749-8f04-0b0cddca0c86.png)

2023-04-27 14:54 UTC, fcurella commented
@JsonVladimir I'm not seeing `--line-length 120` on the second command you called. You can just run `make lint` and it should run it with the correct arguments for you

2023-05-02 14:03 UTC, fcurella requested changes
Could you check the failing tests?

2023-05-02 14:03 UTC, fcurella commented on tests/providers/test_bank.py
> +            assert re.fullmatch(r"\d{2}[A-Z]{4}}\d{18}", iban[2:])
I think I see an extra `}` in `{4}}`

2023-05-08 18:15 UTC, fcurella requested changes

2023-05-08 18:15 UTC, fcurella commented on tests/providers/test_phone_number.py
> +            phone_number = faker.phone_number_pe()
the method is called `phone_number()`:

```suggestion
            phone_number = faker.phone_number()
```

2023-05-16 15:18 UTC, fcurella requested changes

2023-05-16 15:18 UTC, fcurella commented on tests/providers/test_phone_number.py
> +    pass
Can we actually test something? :P

2023-08-29 01:45 UTC, closed without merging