adding state_code and state API
joke2k/faker pull request #1864
Opened 2023-05-11 14:03 UTC by Sbhat92

### What does this change

Adds state_code() API to address provider in en_US and state_name() in en_IN

### What was wrong

Address provider did not have state() and state_code() APIs

### How this fixes it
Adds the above API and corresponding test cases

Fixes #1845

2023-05-16 15:57 UTC, fcurella requested changes
Thank you! Could you run `make lint` to fix the formatting issues?

2023-06-01 16:25 UTC, fcurella commented on tests/providers/test_address.py
> +            assert not isinstance(state_code, str)
Shouldn't `state_code` BE a string?

2023-06-01 16:26 UTC, fcurella requested changes
Can you fix the new test?

2023-07-09 13:37 UTC, weedySeaDragon commented
This would be awesome to have! @Sbhat92 -- do you have the time to finish this?

2023-10-23 01:45 UTC, closed without merging