add bank uk_UA
joke2k/faker pull request #1973
Opened 2024-01-12 13:09 UTC by SanderFtn

add provider.bank for uk_UA localization

2024-01-12 13:19 UTC, stefan6419846 commented
Could you please add corresponding tests as well?

2024-01-12 14:20 UTC, SanderFtn commented
Yes.
Add some tests with new commit.

2024-01-19 16:04 UTC, fcurella requested changes

2024-01-19 16:04 UTC, fcurella commented on tests/providers/test_bank.py
> +class TestUkUA:
The capitalization is actually meaningful here, because of how we run tests.

```suggestion
class TestUkUa:
```

2024-01-19 16:13 UTC, fcurella approved these changes
Thank you!

2024-01-19 16:16 UTC, merged

2024-01-19 16:23 UTC, SanderFtn commented
Thank you too!