Typo fix - prefix for male BG names
joke2k/faker pull request #2004
Opened 2024-03-07 17:30 UTC by DimitarVanguelov

The Bulgarian person provider used `prefix_female` instead of `prefix_male` within `formats_male`.

2024-03-11 15:07 UTC, lozik4 approved these changes

2024-03-11 15:16 UTC, lozik4 commented
@DimitarVanguelov maybe you will add some tests?

2024-03-12 19:49 UTC, lozik4 commented
> Hi @lozik4, I'd be happy to contribute but could use some guidance as to how to test for this sort of thing :)

@DimitarVanguelov
For example
```
class TestBgBg(unittest.TestCase):
    def setUp(self):
        self.fake = Faker("bg-BG")
        Faker.seed(0)

    def test_name(self):
        for _ in range(100):
            name = self.fake.name_male()
```
name will be used template, prefix must be in prefix_male
Your provider doesn't have anything tests. You may write some tests in test_person.py file. 
In this file lot of test in another localization, can be examples for you.

2024-03-12 21:28 UTC, DimitarVanguelov commented
Thanks, I will look into this. 

> Your provider doesn't have anything tests.

Just in case there is any confusion, I did not write this provider, I was just perusing the code and found the typo.

In any case, thanks again and Слава Україні!

2024-03-13 14:59 UTC, fcurella requested changes
Thank you!

2024-03-13 15:00 UTC, merged