Add providers vi_VN ( Viet Nam )
joke2k/faker pull request #2076
Opened 2024-07-26 16:51 UTC by ntd1683

### What does this change

Adds Vietnamese language support (vi_VN) with providers for address, color, company, currency, date_time, job, lorem, person, and phone.

### What was wrong

The project lacked support for the Vietnamese locale, limiting its ability to generate localized data.

### How this fixes it

Introduces Vietnamese-specific data for address, color, company, currency, date_time, job, lorem, person, and phone.

Fixes #2075

2024-07-27 13:13 UTC, ntd1683 commented
@joke2k I have added the Vietnamese language, I checked it but there is an error due to your old code. I hope you can look and approve, I see you don't have Vietnamese yet.

2024-07-27 15:15 UTC, stefan6419846 commented
The typing failures have already been discussed in another PR. Apart from this, could you please add some source indicators for the new data?

2024-07-27 17:04 UTC, ntd1683 commented
> Các lỗi đánh máy đã được thảo luận trong một PR khác. Ngoài ra, bạn có thể vui lòng thêm một số chỉ số nguồn cho dữ liệu mới không?

ok I will add the source right away

2024-08-12 15:23 UTC, fcurella requested changes

2024-08-12 15:23 UTC, fcurella commented on faker/providers/person/vi_VN/__init__.py
> +    formats_female = (
We need data source for names. Please refer to our [coding style](https://github.com/joke2k/faker/blob/master/docs/coding_style.rst#data-sets)

2024-08-21 13:42 UTC, ntd1683 commented
@fcurella  Hello, do I need to edit anything else to contribute to your project? Because I see that in my country, many people use your products

2024-08-21 15:16 UTC, fcurella approved these changes

2024-08-21 15:31 UTC, merged